### ISSUE TITLE
Vendorlist is not sorted 

### ISSUE THREAD

**Issue by CanardSauvage** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#10]
The vendorlist.json from IAB is not sorted by ID by default. But the range takes the first and last entry of the array, which results in a wrong consent-string.

For example https://vendorlist.consensu.org/v-20/vendorlist.json starts with ID 8 and ends with ID 90, as the array is not sorted. If you give a consent to all vendors, you get this constent string:

BOOQUp9OOQU3FABABBENAU-AAAALeABgAQALQA
```json
{
  "cookieVersion": 1,
  "created": "2018-05-24T09:35:46.900Z",
  "lastUpdated": "2018-05-24T09:37:10.900Z",
  "cmpId": 1,
  "cmpVersion": 1,
  "consentScreen": 1,
  "consentLanguage": "EN",
  "vendorListVersion": 20,
  "purposeIdBitString": "111110000000000000000000",
  "maxVendorId": 183,
  "isRange": true,
  "defaultConsent": false,
  "numEntries": 1,
  "vendorRangeList": [
    {
      "isRange": true,
      "startVendorId": 8,
      "endVendorId": 90
    }
  ]
}
```

The range is wrong. It needs to be 1 - 183 --> sort the array of vendors first

Update/edit: I understood defaultConsent wrong and corrected this ticket.

**Comment by jawadst** [comment]
Are you sure that you are using the latest version? This should have been fixed (see https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-JS/commit/b7f4a5f5163a92893bcb31fb5a462b4a86d86859) as we are now sorting the vendors in the library.

**Comment by jawadst** [comment]
And just to be clear from your edit: you are getting the result you expected, right?

**Comment by CanardSauvage** [comment]
We did use an older version 1.2.1, sorry. I didn't check newer versions.
