### ISSUE TITLE
defaultConsent is not optimized

### ISSUE THREAD

**Issue by Waschnick** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#11]
If every vendor is true, I get this result (the range is wrong, see #10, but it's more about we really need the range):

BOOQvTDOOQvTDABABBENAU-AAAALeABgAQALQA

```json
{
  "cookieVersion": 1,
  "created": "2018-05-24T12:37:39.500Z",
  "lastUpdated": "2018-05-24T12:37:39.500Z",
  "cmpId": 1,
  "cmpVersion": 1,
  "consentScreen": 1,
  "consentLanguage": "EN",
  "vendorListVersion": 20,
  "purposeIdBitString": "111110000000000000000000",
  "maxVendorId": 183,
  "isRange": true,
  "defaultConsent": false,
  "numEntries": 1,
  "vendorRangeList": [
    {
      "isRange": true,
      "startVendorId": 8,
      "endVendorId": 90
    }
  ]
}
```

But I would expect it to be:

```json
{
  "cookieVersion": 1,
  "created": "2018-05-24T12:37:39.500Z",
  "lastUpdated": "2018-05-24T12:37:39.500Z",
  "cmpId": 1,
  "cmpVersion": 1,
  "consentScreen": 1,
  "consentLanguage": "EN",
  "vendorListVersion": 20,
  "purposeIdBitString": "111110000000000000000000",
  "maxVendorId": 183,
  "isRange": true,
  "defaultConsent": true,
  "numEntries": 0,
  "vendorRangeList": []
}
```

**Comment by jawadst** [comment]
You are right although that seems like a very marginal improvement and wouldn't save much space.  
We always encode with `defaultConsent: false` in the current version so I guess there are other cases that could be optimized as well.

**Comment by ltparis2018** [comment]
It seems that new version (1.2.4) does not create a range anymore if all vendors are allowed.
I set the global vendor list (version 27 in our tests) and then a list of ids of all vendors (from this global vendor list) using setVendorsAllowed().
Library version 1.2.1 gives me the following consent string: BOOk8eaOOk8eaBQABBENAb-AAAAT2ABgACAnoA
```
{
  "cookieVersion": 1,
  "created": "2018-05-30T15:45:45.000Z",
  "lastUpdated": "2018-05-30T15:45:45.000Z",
  "cmpId": 80,
  "cmpVersion": 1,
  "consentScreen": 1,
  "consentLanguage": "EN",
  "vendorListVersion": 27,
  "purposeIdBitString": "111110000000000000000000",
  "maxVendorId": 317,
  "isRange": true,
  "defaultConsent": false,
  "numEntries": 1,
  "vendorRangeList": [
    {
      "isRange": true,
      "startVendorId": 1,
      "endVendorId": 317
    }
  ]
}
```
With version 1.2.4 the consent string is a little bit longer (for the same global vendor list and allowed vendors): BOOk-PMOOk-PMBQABBENAb-AAAAT17______b9_3__7_9uz_Kv_K7Xf_nnW0721PVA_rXOz_gE7YRAEIAkA
```
{
  "cookieVersion": 1,
  "created": "2018-05-30T15:57:46.800Z",
  "lastUpdated": "2018-05-30T15:57:46.800Z",
  "cmpId": 80,
  "cmpVersion": 1,
  "consentScreen": 1,
  "consentLanguage": "EN",
  "vendorListVersion": 27,
  "purposeIdBitString": "111110000000000000000000",
  "maxVendorId": 317,
  "isRange": false,
  "vendorIdBitString": "11110111111111111111111111111111111111111110110111111011111111101111111111111111110111111111111011011101100111111110010101011111111110010101110110101110111111111111001111001110101101101001110111101101101010011110101010000001111111010110101110011101100111111111000000001001110110110000100010000000001000010000000001001"
}
```

**Comment by chrispaterson** [comment]
I think this has to do with the fact that there are gaps in the ids.  The ids that are unassigned can't be assumed to be positive consent so every time there is a gap in the range encoding it has to create a range entry.  The SDK creates both entries and then it figures out which is smaller.  I'm not sure of a good alternative solution other than to assume that the gaps have consent?

**Comment by jawadst** [comment]
Assuming that the gaps do not have consent (which is what the current version does) seems to be the correct implementation here.
