### ISSUE TITLE
What is the CmpId for Publishers not using an IAB-Compliant CMP?

### ISSUE THREAD

**Issue by tsanders42** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#12]
should they apply for a custom id? or should they use id=0?

**Comment by CanardSauvage** [comment]
Just [register](https://register.consensu.org/CMP) for 350 EUR as a CMP on the website and you are safe. If you sent a consent-string as a not registered CMP, you are violating the policies. That's more about legal, not about tech.

Technically you could use whatever CMP-ID you want, but it's still legally not valid.

**Comment by tsanders42** [comment]
thnx. registration has been sorted out
