### ISSUE TITLE
Extending to allow for non IAB vendors

### ISSUE THREAD

**Issue by ydennisy** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#14]
Hello,
It is a common use case to want to store consent for non IAB vendors.
Would it be considered a good idea to include such vendors here under another key?
Dennis

**Comment by chrispaterson** [comment]
I think that's outside the scope of this SDK.  This is only for decoding/encoding the Consent String which is heavily depended on the Global Vendor List and each vendor having an ID in that scheme.
