### ISSUE TITLE
Issues with setting HTTP Cookies

### ISSUE THREAD

**Issue by ydennisy** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#16]
Does the framework have any suggestions/best practice/code snippets to show how third party cookies should be set in an ideal world?

The implementation I am working on is having issues cross browser.

Loading a CMP via a script tag on a publisher/advertiser site works well. As does then setting cookies from that domain. 

However then making calls to the server to solicit a Set-Cookie header, does not seem to stick with all browsers.

Some help would be great, as cookies had been decided by the IAB as the storage mechanism, so guidance would be useful.

Thanks,
D

**Comment by chrispaterson** [comment]
I think that might be outside of the scope of the Javascript Consent String SDK.  But yes, any browser that doesn't allow setting of third party cookies will block a global consent string.  Therefore, the consent string will need be placed in the first party domain and will be site specific.
