### ISSUE TITLE
Make it compatible with IE8

### ISSUE THREAD

**Issue by fabiowork** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#19]
I am trying to run the transpiled library in IE8 but it seems that it does not like the following bit:

```
 if (context.method === "throw") {
        if (delegate.iterator.return) {
... etc etc
```

Obviously IE8 does not allow `return` as an object property name so the only way to get around it, is to actually edit the source. That's my understanding at least. Would you be able to tackle this? Thanks

**Comment by chrispaterson** [comment]
In general we are not going to support IE8.  That being said, if you want to change the source code to something equivalent to help with compatibility, then go ahead and make a pull request.
