### ISSUE TITLE
cookie encoding issue

### ISSUE THREAD

**Issue by Mordhak** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#2]
Hi,

There is an issue with encoded cookie value. Encoding and decoding a ConsentString should provide the same values.

Here is the reproduction case

```javascript
let cs = new ConsentString();
cs.setGlobalVendorList(globalVendorList); // retrieved from JSON vendor list url
cs.setVendorsAllowed([8, 12]);
let csEncoded = cs.getConsentString();
cs = new ConsentString(csEncoded);
let allowedVendors = cs.getVendorsAllowed(); // allowedVendors = [8, 9, 10, 11, 12]
// selecting any two consecutive ids with first one lower than second one will produce the bug
```

The issue comes from *convertVendorsToRanges* (encode.js).
```vendors.reduce``` parses vendor ids assuming they are sorted, which is not the case.

Regard,

**Comment by jawadst** [comment]
@Mordhak 
Thanks for the report. This is adressed by https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-JS/pull/3.

**Comment by chrispaterson** [comment]
#3 is pulled in now.  Please update to 1.2.2
