### ISSUE TITLE
Newer version than 1.2.4?

### ISSUE THREAD

**Issue by alexandru** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#21]
Hello,

Is there a pre-release version published by any chance?

I see that on master the types have been corrected in: https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-JS/commit/271e66f2b1b5ecce2db7d49aa7c40cd17e582a4e#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8

**Comment by Devidian** [comment]
I would like to see correct typings too, npm version is not for use with typescript currently :(

**Comment by chrispaterson** [comment]
Hi, sorry for the delay.  I've created a pull request for version 1.3.0 which would include some stuff for the in app specification.  https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-JS/pull/25

**Comment by chrispaterson** [comment]
... it incorporates that commit.  Once the pull request is reviewed I can publish a new version to npm.
