### ISSUE TITLE
Encoding a date object

### ISSUE THREAD

**Issue by vitaliemaldur** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#24]
In `bits.js` line  `53`, the result of `date.getTime() / 100` is a float number. This may result in a wrong encoding because `encodeIntToBits` function that is called there expects an `int` number. 

I think it should be `Math.round(date.getTime() / 100)` as in description of the consent string format [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md#vendor-consent-string-format-).

**Comment by chrispaterson** [comment]
This gets handled in 31 of the same file.  parseInt on a number which lops off the float value.
