### ISSUE TITLE
Providing a ready-to-use minified bundle

### ISSUE THREAD

**Issue by spoutnikz** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#40]
Hello there,

Providing a ready-to-use bundle, concatenated and with resolved dependencies would be a really nice improvement.

Best regards

**Comment by chrispaterson** [comment]
We always imagined that a client-side CMP or node.js server would just include the consent-string.js as a dependency and then they could use whatever bundler they are using for their CMP.  What is the use case for this being an independent bundle?

**Comment by spoutnikz** [comment]
Valid point, though the module is only usable in a web app and a lot of websites are not web apps.

The npm run build command doesn't builds but only transpiles. The requires in the generated files are not usable as is and still need to be resolved.

Because of such I needed to make a temporary module that resolves dependencies with browserify and generate a minified bundle to be included in our websites. I must not be the only one in that case.

Not a big deal but as a client library with such a wide reach it could also provide a minified, ready-to-use standalone bundle (npm run build-standalone for example that would use webpack or browserfiy, with uglifyjs or another minifier for example).

Cheers and thanks for the feedback

**Comment by chrispaterson** [comment]
@spoutnikz would you be willing to create a pull request of what that would look like.  I'm open to it, I just didn't see a use case.  Sounds like you've got a good idea of what it looks like in your head.

**Comment by spoutnikz** [comment]
Hello there,

It's based on a misunderstanding of how the IAB framework is used by the vendors. I initially thought we could just generate a consentString and pass it to a vendor. But most vendors use the full IAB consent framework (with a CMP).

So we will head for another solution. I won't provide a patch because now that I better understand better I realize I was mistaken, and probably not a single vendor will want a solution like what I had in mind.

Sorry for your time, thanks for the feedback!

cheers
