### ISSUE TITLE
v1.4.0 lack of the JS content !

### ISSUE THREAD

**Issue by vincent-ogury** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#41]
Hi

I have installed the consent-string v1.4.0 and here the node_modules directory:
```
ls node_modules/consent-string/
LICENSE		README.md	package.json
```

Did you forget to add the compiled code?

**Comment by mhutfield** [comment]
same

**Comment by chrispaterson** [comment]
Thanks for surfacing this.  I unpublished 1.4.0 and rolled back to 1.3.2.  I'm not sure what happened there with the npm publish, I'll try to investigate.
