### ISSUE TITLE
Dist folder no longer present after 1.3.2

### ISSUE THREAD

**Issue by fernandopasik** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#42]
I tried to update today to version 1.4.1 and I noticed from my lint rules that the import was not resolved. Anyway digging into node_modules folder I saw that instead of the dist folder now there’s the src. So the package is not imported anymore.

Did something change in the last release?

**Comment by chrispaterson** [comment]
Hello, my mistake.  I forgot to run the build command before publishing.  Should be fixed @ 1.4.2

**Comment by fernandopasik** [comment]
@chrispaterson I think a cool suggestion could be to have an npm hook for `preversion` there you could execute the build process

**Comment by fernandopasik** [comment]
In the scripts you could have "preversion": "npm run build"

**Comment by chrispaterson** [comment]
There was a script created in the package.json that is "npm release" which runs "build and publish" but I forgot that it was there so I just ran "npm publish" oops.  Won't let that happen again!
