### ISSUE TITLE
Support for TCF version 2

### ISSUE THREAD

**Issue by hemdagem** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#44]
Are there plans to support TCF version 2?

**Comment by kirly-af** [comment]
+1

@hemdagem: FYI, I found this repository which could be helpful to you: https://www.npmjs.com/package/@iabtcf/core

**Comment by chrispaterson** [comment]
@hemdagem and @kirly-af that's right v2 is mostly complete in alpha right now.  I'm writing additional tools as well.  the GitHub repo is https://github.com/chrispaterson/iabtcf-es
