### ISSUE TITLE
`getMetadataString` is not implemented

### ISSUE THREAD

**Issue by FGoessler** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#7]
Hi,

the readme states that there should be a method `getMetadataString()` which is helpful to construct the necessary metadata string for the `getVendorConsents` command of the iAB framework.

However this method is not implemented! Was this simply forgotten or intentionally stripped?

**Comment by jawadst** [comment]
@FGoessler That was forgotten. It shouldn't be too hard to implement by using a subset of the full schema to only include the metadata fields, if you want to give it a try.

I think @chrispaterson started working on it but not sure.

**Comment by chrispaterson** [comment]
I haven't had time @jawadst I haven't started on it. 
@FGoessler the feature was added after the first rev, not intentionally stripped or forgotten

**Comment by chrispaterson** [comment]
We've got a pull request to review for this!  Thanks @LaurenSpiegel for doing the work!

**Comment by FGoessler** [comment]
Uh nice to hear! Thanks @ @LaurenSpiegel! Looking forward for the next release with this feature included.
