### ISSUE TITLE
CMP-SDK-JS

### ISSUE THREAD

**Issue by victuxbb** [InteractiveAdvertisingBureau/Consent-String-SDK-JS#8]
Hi! I'm working in @schibsted spain and starting to implement for our webs the GDPR.
We are interested in having a library to handle all stuff related with CMP, like in this repo https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/tree/master/reference but without mixing presentation and logic ;)
I found this repo of consent string like an isolated concept and that's the idea we want to follow so I was wondering if it's possible that you create a repo like this for only the concept of CMP (CMP-SDK-JS perhaps ? ) and we can help you with 100% dedication doing PR's.
My main idea is to rewrite this https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/reference/src/lib/cmp.js using Promises to deal with async and use some architectural concepts to organize the code and the responsabilities.
Main goal is to not be coupled to presentation so anyone will can use this library to manage consents using whatever they want to use for presentation (react, cycle or whatever framework)

**Comment by chrispaterson** [comment]
That was the main idea behind this SDK toolkit for just the consent string.  What would the CMP-SDK-JS offer that this one doesn't?  I wanted to break apart the various tools to manage the pieces of the Transparency and Consent Framework.  What other tools would you like to see?  I think we are of the same spirit, I just want to know what that looks like to you.  Thanks!

**Comment by ptomasroos** [comment]
I think this is a great idea.

**Comment by CanardSauvage** [comment]
Hey @victuxbb our CMP-Solution https://github.com/as-ideas/oil is OpenSource and you can fork it. It is compatible with IE9 and uses Promises. It uses this library to decode/encode the consent-string. Feel free to have a look.

**Comment by victuxbb** [comment]
@chrispaterson seems that there is already a library doing more things over your library I will take a look but seems a initial good approach of what I had in mind, thanks anyway!
@CanardSauvage I will take a look for sure! thanks
